const Details = {
  Bhisma: {
    Name: "Bhishma Pitamaha",

    Introduction: `Bhishma was a prominent character in the Hindu epic, the Mahabharata. He was the son of King Shantanu and the goddess Ganga, and was known for his unwavering devotion and loyalty to his family, as well as his strength and valor as a warrior. Bhishma played a key role in the great battle of Kurukshetra, where he fought on behalf of his half-brother Dhritarashtra and his nephews, the Kauravas. Despite his affiliation with the oppressors, Bhishma was renowned for his sense of fairness and justice, and was respected by both sides of the conflict. Throughout his life, Bhishma demonstrated the importance of duty, loyalty, and the balance between right and wrong.`,
    FairRole: `Bhishma's life in the Mahabharata teaches many valuable lessons. He was known for his unwavering devotion to his family and his strong sense of duty, which he upheld even in the face of personal suffering and sacrifice. Bhishma also demonstrated the importance of loyalty and the ability to keep one's word, as he honored his vow of celibacy and remained a lifelong bachelor despite being offered the opportunity to marry and have children. Furthermore, Bhishma was a model of fairness and justice, upholding the principles of dharma even when it meant siding against his own family. He also showed the importance of selflessness and the ability to put aside personal desires for the greater good, as he voluntarily stepped down from the throne in favor of his younger brother. These qualities demonstrate the importance of integrity, selflessness, and the balance between right and wrong.`,
    UnfairRole: `Although Bhishma was widely respected for his wisdom, virtue, and loyalty, he also had a darker side in the Mahabharata. He supported the Kauravas in the great battle of Kurukshetra, even though he knew that their actions were unjust. He also played a role in the abduction of Draupadi, the wife of the Pandavas, and failed to speak out against her mistreatment. This caused a rift between Bhishma and the Pandavas and ultimately contributed to the outbreak of the war. These actions suggest that Bhishma was not immune to the pressures of loyalty and the desire to maintain the status quo, even when it meant overlooking the principles of dharma and justice.`,
  },

  Krishna: {
    Name: "Shree Krishna",
    Introduction: `Krishna is one of the central figures in the Hindu epic, Mahabharata. He was a prince of the Yadava dynasty and was considered to be an incarnation of Lord Vishnu. Krishna is known for his wisdom, bravery, and leadership skills and played a key role in the great battle of Kurukshetra, where he acted as the charioteer and advisor to the Pandavas.`,
    FairRole: `Krishna is considered to be a symbol of selflessness, devotion, and duty. He lived his life with a sense of purpose and always placed the needs of others before his own. Krishna's teachings and lessons in the Mahabharata are still relevant today, and they encourage people to lead a life of virtue, compassion, and to always act in the best interests of others.`,
    UnfairRole: `While Krishna is often portrayed as a divine and virtuous figure, he also had a darker side to his personality. In the Mahabharata, Krishna was known to use his powers and influence to manipulate situations and people in order to achieve his goals. He also sanctioned the use of violence and war, which resulted in the deaths of many innocent people. This darker aspect of Krishna's character highlights the complexities of human nature and the duality of good and evil.`,
  },
  Karna: {
    Name: "Karna",
    Introduction: `Karna is one of the central characters in the Hindu epic Mahabharata. He was the son of Surya, the sun god, and Kunti, who was unmarried at the time of his birth. Karna was born with divine armor and earrings, which protected him from death. Despite his noble birth, he was raised by a charioteer and considered himself a member of the lower caste.`,
    FairRole: `Karna's life teaches several important lessons, including humility, generosity, and bravery. He was a selfless person who was always willing to help others, even at the cost of his own life. He never lost faith in his friends and was always ready to offer his support. Karna's unwavering devotion to his friends and family, as well as his courage in the face of adversity, make him a role model for future generations.`,
    UnfairRole: `Despite his many positive qualities, Karna also had some negative traits. He was prone to anger and had a tendency to act impulsively. He was also fiercely competitive and struggled with jealousy, especially towards his half-brothers, the Pandavas. These negative traits ultimately led to his downfall, as he became entangled in the battle between the Pandavas and the Kauravas, which ultimately resulted in his death. Despite his mistakes, Karna remains an important and revered figure in Hindu mythology.`},
  Duryodhana: {
    Name: "Duryodhana",
    Introduction: ``,
    FairRole: `Some good lessons from Duryodhana's life in the Mahabharata include his unwavering loyalty and devotion to his family and kingdom. He was also a skilled warrior and leader, who was willing to take calculated risks to achieve his goals. Additionally, Duryodhana showed a strong will and determination, never giving up in the face of adversity, even in the face of defeat.

`,
    UnfairRole: `However, Duryodhana had a dark side as well. He was known for his greed, arrogance, and cruelty, which led him to make many unethical and immoral decisions throughout the course of the epic. He was also envious of the Pandavas, and went to great lengths to harm them and their kingdom. This included trying to kill the Pandavas in various ways, as well as trying to cheat them out of their rightful share of the kingdom through deceit and manipulation. Ultimately, his actions led to the great Kurukshetra War, which resulted in the death of many brave warriors and the eventual downfall of the Kuru Kingdom.`,
  },
  Draupadi: {
    Name: "Draupadi",
    Introduction: ``,
    FairRole: `
   `,
    UnfairRole: ``,
  },
  Dhritrastra: {
    Name: "Dhritrastra",
    Introduction: ``,
    FairRole: ``,
    UnfairRole: ``,
  },
  Dronacharya: {
    Name: "Duryodhana",
    Introduction: ``,
    FairRole: ``,
    UnfairRole: ``,
  },
  Arjuna: {
    Name: "Arjuna",
    Introduction: `Arjuna is one of the central characters in the Hindu epic, the Mahabharata. He was the third of the five Pandava brothers and was considered to be one of the greatest warriors of his time. Arjuna was known for his bravery, skill, and devotion to dharma (duty and righteousness). He was also a close friend and devotee of Lord Krishna, who served as his charioteer and advisor during the Kurukshetra War. Arjuna's journey of self-discovery and growth, as well as his internal struggle over the morality of war, form a major part of the Mahabharata's narrative.`,
    FairRole: `Arjuna's life in the Hindu epic, the Mahabharata, offers several important lessons for readers. One of the key lessons is the importance of dharma, or duty and righteousness, as seen in Arjuna's struggle over the morality of war. The power of devotion is also evident in Arjuna's relationship with Lord Krishna, who served as his advisor and charioteer. Arjuna's journey of self-discovery and growth serves as a reminder of the importance of introspection and self-awareness. His bravery and determination in the face of adversity demonstrate the power of perseverance. Finally, Arjuna's close bond with his brothers and with Lord Krishna highlight the importance of friendship and loyalty in our lives. These lessons from Arjuna's life serve as a guide for personal growth and development.`,
    UnfairRole: `In the Hindu epic, the Mahabharata, Arjuna is not depicted as having a dark side, but rather as a complex hero with flaws and strengths. He was known for his bravery, skill, and devotion to dharma, but he also struggled with feelings of doubt, fear, and indecision at times. For example, before the Kurukshetra War, Arjuna was consumed by feelings of doubt about the morality of fighting against his own family and friends, which caused him to question his duty as a warrior. This inner struggle highlights his human qualities and makes him a relatable character for readers. While Arjuna is not depicted as having a "dark side" in the traditional sense, his flaws and internal struggles serve to make him a well-rounded and realistic hero in the epic.`,
  },
  Bhima: {
    Name: "Bhima",
    Introduction: `Bhima is one of the five Pandava brothers in the Hindu epic, the Mahabharata. He is known for his great strength and bravery, as well as his quick wit and cunning nature. Bhima was born to Kunti and the wind-god Vayu, and was the second-eldest of the Pandavas. He played a key role in the Kurukshetra War and was responsible for killing several of the Kauravas' most powerful warriors, including the demon-like Dushasana. Despite his fearsome reputation, Bhima was also known for his love and loyalty to his family and friends, and was often relied upon for his courage and determination in the face of adversity.`,
    FairRole: `Bhima's life in the Hindu epic, the Mahabharata, offers several important lessons for readers. One of the key lessons is the importance of strength and bravery. Bhima's physical strength and fearlessness in battle serve as a reminder of the power of courage and determination in the face of adversity. He also highlights the importance of cunning and wit, as his quick thinking and strategic nature often proved valuable in battle. Bhima's deep love and loyalty to his family and friends also underscore the importance of relationships and the power of bonds between individuals. Finally, Bhima's determination and perseverance serve as an example of the importance of never giving up, even in the face of overwhelming odds. These lessons from Bhima's life serve as a guide for personal growth and development.`,
    UnfairRole: `In the Hindu epic, the Mahabharata, Bhima is depicted as having a hot-headed and impulsive nature, which sometimes leads him to act rashly and make decisions that are not in line with dharma. For example, he is known for his violent tendencies and his thirst for revenge against the Kauravas, which at times threatens to undermine the Pandavas' cause. He also has a tendency to become consumed by anger and rage, which can lead him to behave in destructive and even cruel ways. However, despite these flaws, Bhima is also depicted as being deeply loving and loyal to his family, and his actions are often motivated by a desire to protect them. In summary, Bhima's character in the Mahabharata is complex and multifaceted, with both admirable qualities and darker traits that serve to make him a well-rounded and realistic hero in the epic.`,
  },
  Abhimanyu: {
    Name: "Abhimanyu",
    Introduction: `Abhimanyu was the son of Arjuna and Subhadra in the Hindu epic, the Mahabharata. He was a skilled warrior and known for his bravery and valor. Abhimanyu was trained in the use of weapons by his father, and was considered to be a prodigy in battle. Despite his young age, he played a key role in the Kurukshetra War, where he was known for his fearlessness and determination. Abhimanyu is most famous for his heroic actions in the Chakravyuha, a military formation created by the Kauravas, where he single-handedly penetrated the formation and fought against impossible odds before being killed. Abhimanyu's bravery and unwavering commitment to his duty serve as a reminder of the power of courage and determination in the face of adversity.`,
    FairRole: `The life of Abhimanyu in the Hindu epic, the Mahabharata, teaches several important lessons for readers. Firstly, Abhimanyu's bravery and fearlessness serve as a reminder of the power of courage and determination in the face of adversity. He was willing to put himself in harm's way to protect his family and friends, and his unwavering commitment to his duty is an inspiration for readers. Secondly, Abhimanyu's skill and mastery of weapons highlights the importance of discipline and hard work. He was trained by his father, Arjuna, and became a prodigy in battle at a young age due to his dedication and perseverance. Finally, Abhimanyu's tragic death serves as a reminder of the fragility of life and the importance of valuing every moment. His life and legacy serve as a reminder of the impact that one person can have, even in the face of seemingly insurmountable odds. These lessons from Abhimanyu's life serve as a guide for personal growth and development.`,
    UnfairRole: `Abhimanyu's character in the Hindu epic, the Mahabharata, is mostly depicted as being noble, brave, and virtuous. However, he does not have any significant negative traits or dark sides. He is portrayed as a skilled warrior, brave and loyal to his family, and dedicated to his duty. His life is a testament to the power of courage and determination, and his tragic death serves as a reminder of the fragility of life. Therefore, there is no notable "dark side" to Abhimanyu's life in the Mahabharata.`,
  },
  Yudhishthira: {
    Name: "Yudhishthira",
    Introduction: `Yudhishthir, also known as Dharmaraja, was the eldest of the five Pandavas in the Hindu epic, the Mahabharata. He was known for his strong sense of righteousness and his unwavering commitment to dharma, the moral law that governs human behavior. Yudhishthir was the king of Hastinapura and was revered for his wisdom, compassion, and integrity. Despite his many virtues, Yudhishthir also had his weaknesses, including a tendency to be overly truthful and a tendency to be swayed by his emotions. Throughout the course of the epic, Yudhishthir grapples with his own moral dilemmas and emerges as a complex and flawed hero, whose life teaches important lessons about the nature of dharma and the challenges of leadership.`,
    FairRole: `The life of Yudhishthir in the Hindu epic, the Mahabharata, teaches several important lessons for readers. Firstly, Yudhishthir's unwavering commitment to dharma, the moral law that governs human behavior, highlights the importance of living a life guided by moral principles. He consistently strives to do what is right and just, even when it is difficult or unpopular. Secondly, Yudhishthir's struggles with his own weaknesses and moral dilemmas serve as a reminder that even the wisest and most virtuous individuals face challenges in their lives. He grapples with his own tendencies towards excessive truthfulness and emotional instability, and his experiences serve as a guide for personal growth and development. Finally, Yudhishthir's leadership and wisdom serve as a reminder of the importance of compassion and good judgment in leadership. Despite his many virtues, he is a complex and flawed hero, whose life teaches important lessons about the nature of dharma and the challenges of leadership.`,
    UnfairRole: `Yudhishthir, also known as Dharmaraja, is generally portrayed as a virtuous and wise character in the Hindu epic, the Mahabharata. However, he does have some negative traits and weaknesses that can be considered his "dark side." For example, he has a tendency to be overly truthful, which at times can be harmful to himself and those around him. He also struggles with his emotions and can be swayed by his desires, leading to impulsive and sometimes rash decisions. Additionally, he is prone to gambling, which ultimately leads to the loss of his kingdom and his wife. These flaws in Yudhishthir's character serve as a reminder that even the most virtuous individuals are not immune to human weaknesses and flaws, and they add depth and complexity to his character in the epic.`,
  },
  Nakul_and_Sahdev: {
    Name: "Nakul and Sahadeva",
    Introduction: `Nakul and Sahadeva were two of the five Pandavas in the Hindu epic, the Mahabharata. They were the younger twin brothers of the Pandavas and were known for their skills as warriors and their devotion to their family. Nakul was known for his handsomeness and charm, while Sahadeva was renowned for his knowledge and wisdom. The two brothers were instrumental in the Pandavas' victory in the great war of Kurukshetra, and they both played important roles in the events that shaped the epic. Despite their bravery and loyalty, Nakul and Sahadeva were often overshadowed by their older brothers, Bhima, Arjuna, and Yudhishthir, and are not as well known as the other Pandavas in popular culture. Nevertheless, their lives and stories serve as an important part of the Mahabharata and provide important lessons for readers.`,
    FairRole: `The lives of Nakul and Sahadeva in the Hindu epic, the Mahabharata, offer several valuable lessons for readers. Firstly, their devotion to their family and their unwavering loyalty to their brothers, the Pandavas, highlights the importance of strong family bonds and the power of solidarity in times of crisis. Secondly, their skills as warriors and their bravery in battle serve as a reminder of the importance of courage and determination in the face of adversity. Thirdly, Nakul's handsomeness and charm and Sahadeva's wisdom and knowledge demonstrate the importance of cultivating multiple talents and strengths in order to be well-rounded and successful individuals. Finally, the twins' relationships with their brothers and their role in the great war of Kurukshetra serve as a reminder of the interconnectedness of individuals and the importance of considering the perspectives and needs of others. Despite not being as well-known as some of their other brothers, the lives of Nakul and Sahadeva offer valuable lessons for readers and contribute to the rich tapestry of the Mahabharata.`,
    UnfairRole: `In the Hindu epic, the Mahabharata, Nakul and Sahadeva are often portrayed as minor characters and are not given as much attention as some of the other Pandavas. As a result, there is not much information available about their negative traits or weaknesses, and their characters are largely depicted in a positive light. However, it is possible that the lack of attention given to them could be seen as a flaw in and of itself, as it suggests that they were not considered as important or significant as their older brothers. Additionally, their lack of individuality and their tendency to blend into the background could be seen as a weakness, as it highlights their dependence on their brothers and their lack of independence. These are potential areas where the characters of Nakul and Sahadeva could be seen as having a "dark side," but overall they are largely portrayed as positive and virtuous individuals in the epic.`,
  },
  Eklavya: {
    Name: "Eklavya",
    Introduction: `Eklavya was a character in the Hindu epic, the Mahabharata. He was a prince of the Nishadha tribe and was known for his exceptional archery skills. Despite being born into a lower-caste tribe, Eklavya aspired to become a great warrior and archer. He practiced on his own, using a clay statue of the renowned archer guru, Dronacharya, as his teacher. His skill and dedication eventually caught the attention of Dronacharya, who was shocked to see that a prince from a lower-caste tribe had surpassed his own students, including the Pandavas prince Arjuna. To ensure that Arjuna remained the greatest archer in the land, Dronacharya demanded that Eklavya cut off his right thumb as guru-dakshina, or a teacher's fee. Despite the high cost, Eklavya obediently cut off his thumb and gave it to Dronacharya. This act of selflessness and obedience to his teacher made Eklavya an exemplar of devotion and dedication to one's craft, and he remains a revered figure in Hindu mythology to this day.`,
    FairRole: `Eklavya's life in the Hindu epic, the Mahabharata, teaches several important lessons. Firstly, his unwavering dedication and self-discipline in the pursuit of his passion for archery despite the challenges he faced as a prince of a lower-caste tribe is an inspiration to all. He teaches us that with hard work, perseverance and determination, one can achieve great things. Secondly, his obedience to his teacher and willingness to pay the high cost of guru-dakshina is a lesson in the value of devotion to one's guru and the importance of respecting traditional practices and customs. Finally, Eklavya's humility in the face of discrimination based on his caste is a lesson in the importance of self-respect and dignity, and an encouragement to stand up for one's beliefs even in the face of adversity. These lessons from Eklavya's life make him an enduring figure in Hindu mythology, and an example for people of all walks of life.`,
    UnfairRole: `In the Hindu epic, the Mahabharata, the dark side of Eklavya's life stems from his being born into a lower-caste tribe, which led to discrimination and prejudice from those of higher castes, including the renowned archery guru, Dronacharya. Despite his exceptional archery skills, Eklavya was not accepted as a student by Dronacharya because of his lower-caste status, and he was forced to practice on his own using a clay statue of Dronacharya as his teacher. When Dronacharya finally became aware of Eklavya's skills and realized that he had surpassed his own students, including the Pandavas prince Arjuna, he demanded that Eklavya cut off his right thumb as guru-dakshina. This act of cruelty by Dronacharya was a result of the deep-seated prejudice and discrimination that existed in the society of the time and highlights the negative effects of such attitudes.`,
  },
  Kripacharya: {
    Name: "Kripacharya",
    Introduction: `Kripacharya is a character in the Hindu epic, the Mahabharata. He is the son of the sage, Rishi Kripa, and is a teacher of martial arts and military tactics. Kripacharya served as a mentor and teacher to both the Pandavas and Kauravas, and was known for his wisdom and skill as a warrior. During the great battle of Kurukshetra, he fought on the side of the Kauravas and was one of their most trusted advisors. Despite his loyalty to the Kauravas, Kripacharya was known for his impartiality and fairness, and was respected by both sides of the conflict. In the aftermath of the battle, he became the spiritual teacher of Parikshit, the grandson of the Pandavas, and continued to impart his wisdom to future generations.`,
    FairRole: `In the Hindu epic, the Mahabharata, Kripacharya's life teaches several valuable lessons. Firstly, Kripacharya's dedication to imparting knowledge and skills to both the Pandavas and Kauravas, despite the conflict between them, demonstrates the importance of imparting wisdom and education impartially and without bias. Secondly, his ability to remain neutral and impartial, even in the face of intense conflict, highlights the importance of maintaining one's values and principles in the face of adversity. Additionally, Kripacharya's bravery and skills as a warrior show the value of being prepared and equipped to face challenges in life. Finally, his role as a mentor and spiritual teacher to future generations highlights the importance of passing on one's knowledge and wisdom to future generations and being a positive influence on the world.`,
    UnfairRole: `In the Mahabharata, there is no significant mention of a "dark side" to Kripacharya's character. However, his loyalty to the Kauravas, who were the oppressors and antagonists in the great battle of Kurukshetra, may be seen as a negative aspect of his character. Additionally, as a warrior, he fought in the battle and participated in acts of violence. However, it should be noted that in the context of the story, he was bound by his duty as a warrior and teacher to the Kauravas and was not depicted as acting out of cruelty or malevolence.`,
  },
  Ashwatthama: {
    Name: "Ashwatthama",
    Introduction: `In the Hindu epic, the Mahabharata, Ashwatthama is the son of Dronacharya, one of the greatest warriors and teachers of his time. He is depicted as a warrior of exceptional skill and bravery, who is a key player in the great battle of Kurukshetra. Ashwatthama is known for his devotion to his father and his loyalty to the Kauravas, which puts him at odds with the Pandavas. Despite his association with the Kauravas, he is also known for his extreme martial prowess and ferocity in battle, which earns him a reputation as one of the fiercest warriors of his time.`,
    FairRole: `Ashwatthama's life in the Mahabharata teaches several important lessons. Firstly, the devotion and loyalty he demonstrates towards his father Dronacharya, despite his father's affiliation with the oppressors in the great battle of Kurukshetra, is a testament to the value of filial piety. Additionally, Ashwatthama's martial prowess and bravery in battle serve as an example of the importance of courage and determination. However, it is important to note that his actions in the battle, including the killing of innocent warriors while they slept, serve as a cautionary tale against the dangers of blind loyalty and the abuse of power. Overall, the character of Ashwatthama highlights the complexity of human nature and the importance of making moral and ethical decisions, even in the face of difficult circumstances.`,
    UnfairRole: `The dark side of Ashwatthama's life in the Mahabharata is seen in his actions during the great battle of Kurukshetra. Despite his skill and bravery as a warrior, he is depicted as cruel and unethical in his methods, such as killing innocent warriors while they slept. He is also depicted as being vengeful and seeking retribution, even if it means breaking the rules of engagement in battle. These actions demonstrate the dangers of unchecked anger and the consequences of moral decay in the face of power and the desire for victory. Ashwatthama's actions serve as a reminder of the importance of maintaining one's integrity and ethics, even in the face of adversity.`,
  },
};

export default Details;


// short introduction of duryodhana in mahabharata

// good lessions from duryodhana life in mahabharata
// write it in a paragraph


// dark side from the life of duryodhana in mahabharata

// write in a separate paragraph each
